### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by phasis68** [Naddiseo/dart-sprintf#33]
dart-sprintf cannot handle Infinity or NaN
For Infinity:
```
  var a = 1.0 / 0;
  print("a:$a");
  print(sprintf("a:%g", [a]));
```
```
a:Infinity
Unhandled exception:
Unsupported operation: Infinity or NaN toInt
#0      double.toInt (dart:core-patch/double.dart)
#1      double.truncate (dart:core-patch/double.dart:197:21)
#2      new FloatFormatter (package:sprintf/src/formatters/float_formatter.dart:28:22)
#3      new PrintFormat.<anonymous closure> (package:sprintf/src/sprintf_impl.dart:23:28)
#4      PrintFormat.call (package:sprintf/src/sprintf_impl.dart:88:39)
```
For NaN:
```
  var a = 0.0 / 0;
  print("a:$a");
  print(sprintf("a:%g", [a]));
```
```
a:NaN
Unhandled exception:
Unsupported operation: Infinity or NaN toInt
#0      double.toInt (dart:core-patch/double.dart)
#1      double.truncate (dart:core-patch/double.dart:197:21)
#2      new FloatFormatter (package:sprintf/src/formatters/float_formatter.dart:28:22)
#3      new PrintFormat.<anonymous closure> (package:sprintf/src/sprintf_impl.dart:23:28)
#4      PrintFormat.call (package:sprintf/src/sprintf_impl.dart:88:39)
```

**Comment by Naddiseo** [comment]
Thanks for spotting that! v7.0.0 should have the fix, please let me know if you have any other issues!
